version: "3"

services:
  scrape:
    image: openstates/openstates
    environment:
    - MYSQL_HOST=mysql
    - DATABASE_URL=postgres://postgres:secret@postgres:5432/openstates
    - NEW_YORK_API_KEY
    - INDIANA_API_KEY
    - PUPA_ARGS
    volumes:
    - .:/opt/openstates/openstates/
    entrypoint: /opt/openstates/openstates/pupa-scrape.sh

  postgres:
    image: mdillon/postgis:10-alpine
    ports:
    # Expose Postgres to the host on port 5433, instead of the
    # default 5432, to avoid conflicts with local Postgres
    - "5433:5432"
    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=openstates

  dbinit:
    image: openstates/openstates
    environment:
    - DATABASE_URL=postgres://postgres:secret@postgres:5432/openstates
    entrypoint: /opt/openstates/openstates/scripts/dbinit.sh
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - postgres

  mysql:
    image: mysql:5.7
    command: mysqld --max_allowed_packet=512M
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=capublic
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  ca-download:
    image: openstates/openstates
    entrypoint: /opt/openstates/openstates/openstates/ca/download.sh
    environment:
    - MYSQL_HOST=mysql
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - mysql
